version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gigaverse-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Gigaverse
      MYSQL_USER: gigaverse
      MYSQL_PASSWORD: teste
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gigaverse-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://gigaverse-mysql:3306/Gigaverse
      SPRING_DATASOURCE_USERNAME: gigaverse
      SPRING_DATASOURCE_PASSWORD: teste
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
    ports:
      - "3306:3306"
    depends_on:
      - mysql

volumes:
  mysql-data:
